### PR TITLE
Added toggle to disable pimping of scala toolchain

### PR DESCRIPTION
**Pull request by lefou**
To disable automatic enrichment of the build model with Scala compiler and dependencies, one can set:

```scala
ScalaModel(
  gav = "g" % "a" % "1.0",
  // other stuff
  pimpScalaToolchain = false
)
```

### CODE REVIEW

**Comment by lefou** [comment]
WDYT, @huntc?

**Comment by huntc** [comment]
You shouldn't need this - just use `MavenModel` instead of `Model`... or am I missing something?

**Comment by lefou** [comment]
Oh, I guess you are right. I must have overlooked Model. So, this PR isn't necessary anymore. :)

**Comment by jvanzyl** [comment]
If everything works correctly maybe you can make an example we can put in:

https://github.com/takari/polyglot-maven-examples

**Comment by lefou** [comment]
Sure. See https://github.com/takari/polyglot-maven-examples/pull/3

**Pull request closed without merging**
